services:
  # Backend API Service (Web Service)
  - type: web
    name: cpp-ai-ide-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: cpp-ai-ide-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://cpp-ai-ide-backend.onrender.com
